### ISSUE TITLE
Tibber weather forecast

### ISSUE THREAD

**Issue by oddi66** [slasktrat/com.tibber#13]
The outside temp has not been updated for atleast a month in the homey device. Correct forecast is working in tibber app.

**Comment by slasktrat** [comment]
Could you try to remove and re-add the home/device in Homey?

**Comment by oddi66** [comment]
Tryed to remove and add 25 min ago and i still have no value on the temprature

**Comment by TheArcturian** [comment]
I have the same problem. Just thought I should create a bug report on it and found this open issue here.

Mine is stuck on an outdoor tempreature of 3.4 degrees and has been so for a month. I have upgraded the Tibber app and restarted it, but it didn't help. Rebooting Homey does not help either.

The independent Tibber app for iOS works fine.

**Comment by TheArcturian** [comment]
I'm running the latest version of Homey (2.0.5) and your Tibber app 1.0.9.

**Comment by slasktrat** [comment]
Found the issue, new version is sent to app store
