### ISSUE TITLE
Feature Request - Trigger at the lowest price the next X hours

### ISSUE THREAD

**Issue by Staasy** [slasktrat/com.tibber#2]
I would like to automatically start the dishwasher and the washing machine when the price is at the lowest during the comming night.

As Tibber foretells the price some time ahead, is it possible to make a trigger for when the price is at the lowest during the next X hours?

**Comment by prj84** [comment]
This is what Tibber reports to SmartThings, maybe this could be used for some flow trigger cards?

Max and Min cards is quite interesting :-)


From ST driver:

State Variables

pricePlus2Hour : 56
pricePlus2HourLabel : @ 23 - 00
priceMaxDay : 63
priceMinDayLabel : Min price @ 03
price : 60
priceNextHourLabel : @ 22 - 23
priceMaxDayLabel : Max price @ 17
currency : NOK: Øre/kWh
priceNextHour : 57
priceMinDay : 52

**Comment by slasktrat** [comment]
Yes, triggers for when reaching lowest/highest price during X next hours is a great idea, will implement :)

**Comment by slasktrat** [comment]
Fixed and updated app sent to Athom for review
