### ISSUE TITLE
Variable "Current price" is not correct at the time it changes

### ISSUE THREAD

**Issue by TheArcturian** [slasktrat/com.tibber#5]
The variable "Current price" is not correct (or updated) at the time it changes. I use it in a flow with a push notification to my phone. When I get notified of a price change based on my criterias, it shows the previous hours price instead of the new current one.

This is an example where I turn off the water heaters if the price is above 0,7 between 07:00 and 20:00:

![image](https://user-images.githubusercontent.com/16746633/50991194-60425580-1514-11e9-8893-5fb2266c8ec0.png)

So it seems that the notification is sent before the value "Current price" is actually updated. This must be a bug as the trigger is "Price changed". It would be great if you could fix that. Thanks!

Setter ellers stor pris på at du har tatt deg tid til å lage Tibber appen for Homey! Glimrende levert! Som du ser i eksemplet så er det en enkel måte å gjøre strømregningen lavere på og varmtvannet er fremdeles varmt gjennom dagen ved normal bruk, takket være deg. :-)

**Comment by slasktrat** [comment]
Hi and thanks a lot for the bug report, I will fix :)

Og takk for det også, godt å høre at appen kommer til nytte! :)

**Comment by TheArcturian** [comment]
Great, takker så mye! :-)

**Comment by slasktrat** [comment]
This is solved and update will be available as soon as it is approved by Athom
