### ISSUE TITLE
Missing current Price in Home app (iPhone/iPad), only Temp available now

### ISSUE THREAD

**Issue by TheArcturian** [slasktrat/com.tibber#6]
In Homey, we can see both Price and Temperature. However, when I see the same object in the "Home" app on an iPad or iPhone, the Price is not available. 

Usually two object would be created in the Home app when a "device" have several properties, but not in this case. I'm not sure if the bug is in the Tibber app or if the HomeKit app is the problem, but I have not seen a similar problem for any of my other multitude of devices. Still running Homey version 1.5.13.

Anyways, it would be great if I could see the current price in the Home app as well. Thanks!

**Comment by TheArcturian** [comment]
I'm using the HomeKit (Sprut1) as that one is much more flexible.

**Comment by slasktrat** [comment]
Caused by limitation outside scope of this app
