### ISSUE TITLE
Missing historical price in insights

### ISSUE THREAD

**Issue by runestadj** [slasktrat/com.tibber#7]
After upgrading too 2.0, I am unable to find historical prices in insight.athom.com

**Comment by slasktrat** [comment]
Hi. Thanks for reporting. There is a bug in 2.0 at the moment, allegedly fixed in the upcoming 2.0.1.
https://github.com/athombv/homey-apps-sdk-issues/issues/39

**Comment by slasktrat** [comment]
Working again with latest firmware from Athom
