### ISSUE TITLE
Tibber Pulse updates freezes

### ISSUE THREAD

**Issue by ingepettersen** [slasktrat/com.tibber#8]
Every 2-3 days, Tibber Pulse data freezes and stops updating. This always happens at midnight. A restart of the app is required to make it come back to life. 

Tibber's own app is always showing updated data, so this is a bug for Homey.

**Comment by slasktrat** [comment]
Thanks for reporting. I have never experienced this myself, so it is a bit hard to troubleshoot, but I have done some minor adjustments that may help. So please let me know if the issue persists after the app has been updated to version 1.0.5

**Comment by ingepettersen** [comment]
Thank you. Will test the new version for a week and provide feedback.

Tibber Pulse on v1.0.4 stopped updating again yesterday, but for the first
time not at midnight. Now it was 18:00.

tor. 14. feb. 2019 kl. 00:50 skrev slasktrat <notifications@github.com>:

**Comment by ingepettersen** [comment]
I'm sorry to say that this issue still persists on Tibber v1.0.6

Pulse stops updating around every 2 days, at random times. Have tried lengthening the update interval to 45 sec. without any effect. 

Want a diagnostics report while frozen?

**Comment by slasktrat** [comment]
Hi. You are very welcome to send diagnostics report.

**Comment by slasktrat** [comment]
The connection should be reconnected on error by the underlying library, but  I've implemented a fail-safe now that will be included in the next update. It will reinitiate the data subscription if no data is received for 10 minutes.

**Comment by ingepettersen** [comment]
Now frozen for the past 2 hours: 3ca93dd7-c353-47b9-b085-329475593553

**Comment by slasktrat** [comment]
Can you try to install 1.0.7 beta?

**Comment by ingepettersen** [comment]
Installed now, will report back within a week 👍🏻

**Comment by slasktrat** [comment]
👍

**Comment by ingepettersen** [comment]
5 days without problems on v1.0.7 beta 😁 I call this issue closed 👏🏻
